### PR TITLE
Support Composer 2 with native Composer Installers

### PR DESCRIPTION
**Pull request by tiefenb**
Support Composer 2 with native Composer Installers instead of hari/pw-module which does not support Composer 2

### CODE REVIEW

**Comment by wanze** [comment]
@tiefenb Cool, thanks! :)

Two questions as I don't know the Composer installer myself:
* Does this also work for new installations with Composer `1`, or is Composer `2` a requirement?
* Is it possible to update the module via `composer update` if the current version is using `hari-pw-module`?

Also I just noticed that we should delete the `composer.lock` file from the repo, because dependencies should not be locked by the module but rather by the consumer's installation.

Cheers 🍻

**Comment by tiefenb** [comment]
Hi @wanze !

- I guess Composer 2 is a requirement - maybe I have time to try it out soon.
- Composer 2 does not support hari-pw-module. This bothered me since many month since Composer 1 is more and more depricated by many packages. But a new solution is made by @daun: https://github.com/composer/installers/pull/472

**Comment by daun** [comment]
`composer/installers` has been around for a while and works with Composer 1 and 2. At least I've been using it that way. No issues I can recall. The switch from `hari` to `composer/installers` has worked well for my modules and should improve compatibility since it supports Composer 1 and 2 while `hari` supports Composer 1 only.

**Comment by wanze** [comment]
Thanks for the nice explanation @tiefenb @daun 👍 

Cheers

**Pull request merged**
